---
apiVersion: ambassador/v0
kind:  Module
name:  authentication
config:
  auth_service: "127.0.0.1:3000"
  path_prefix: "/extauth"
  allowed_headers:
  - "x-extauth-required"
  - "x-authenticated-as"
  - "x-qotm-session"
