---
apiVersion: v1
kind: Service
metadata:
  name: demo2
  annotations:
    ambassador: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  demo2_mapping
      prefix: /demo/
      service: demo2
      weight: 90
spec:
  selector:
    app: demo2
  ports:
    - port: 80
      targetPort: http-api
  type: ClusterIP
