---
sudo: false
language: python
python:
  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

# Do not run in Travis CI when the branch name starts with "nobuild". Primarily
# intended for documentation updates but may be used as an escape hatch for
# other purposes.
branches:
  except:
    - /^nobuild.*$/

services:
  - docker

env:
  global:
    - DOCKER_REGISTRY=-
    - GIT_COMMIT_SHORT="$(git rev-parse --short HEAD)"
    - SCOUT_DISABLE=1

before_install: []

install:
  - pip install -Ur dev-requirements.txt
  - pip install -Ur ambassador/requirements.txt
  - npm install gitbook netlify-cli

before_script:


script:
  - printenv
  - |
    if [[ "$TRAVIS_TAG" == "" && ! "${TRAVIS_PULL_REQUEST_BRANCH}" =~ ^nobuild.* ]]; then
      ./releng/travis-script.sh \
        "${TRAVIS_BRANCH}" \
        "${GIT_COMMIT_SHORT}" \
        "${TRAVIS_TAG}";
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: ./releng/travis-deploy.sh "$(git rev-parse --short HEAD)" "${TRAVIS_TAG}"
    on:
      branch: master
