---
apiVersion: v1
kind: Secret
metadata:
  name: ambassador-certs
  namespace: default
type: Opaque
data: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: ambassador
  name: ambassador
spec:
  type: LoadBalancer
  ports:
  - name: ambassador
    port: 443
    targetPort: 443
  selector:
    service: ambassador
