apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ambassador
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: ambassador
        # service: ambassador-admin
    spec:
      containers:
      - name: ambassador
        image: dwflynn/ambassador:0.1.1
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 8001
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
