apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: ambassador
  name: ambassador
spec:
  type: LoadBalancer
  ports:
  - name: ambassador
    port: 80
    targetPort: 80
  - name: ambassador-admin
    port: 8001
    targetPort: 8001
  selector:
    service: ambassador
