---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  diag_mapping
      prefix: /ambassador/
      rewrite: /ambassador/
      service: 127.0.0.1:8877
spec:
  selector:
    app: ambassador
  ports:
    # The name is still "http", to match up with ambassador-deployment.yaml
    - name: http
      protocol: TCP
      port: 443
      targetPort: 443
  type: NodePort
