---
apiVersion: v1
kind: Secret
metadata:
  name: ambassador-certs
  namespace: default
type: Opaque
data: {{}}
---
apiVersion: v1
kind: Secret
metadata:
  name: ambassador-cacert
  namespace: default
type: Opaque
data: {{}}
