---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: 008-cacert
  # annotations:
  #   getambassador.io/config: |
  #     ---
  #     apiVersion: ambassador/v0
  #     kind:  Module
  #     name:  tls
  #     config:
  #       server:
  #         enabled: True
  #       client:
  #         enabled: True
spec:
  selector:
    service: ambassador
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  type: NodePort
