title: Ambassador
email: hello@datawire.io
author: "Datawire.io"
description: "Ambassador, API Gateway built on Envoy"
keywords: "Ambassador, Envoy, Kubernetes, microservices"

baseurl: ""
url: "http://www.getambassador.io" # the base hostname & protocol for your site
twitter_username: datawireio
github_username:  datawire

# use this to define the categories of your documentation
category-list:
  - "about"
  - "user-guide"

# optionally you can define icon for each category (for the sidebar)
# Doc42 uses Font Awesome
category-icons: [play, code]

# Build settings
markdown: kramdown
