---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  diag_mapping
      prefix: /ambassador/
      rewrite: /ambassador/
      service: 127.0.0.1:8877
      ---
      # Disabling the default diagnostic route
      apiVersion: ambassador/v0
      kind: Module
      name: ambassador
      config:
        diagnostics:
          enabled: false
spec:
  selector:
    app: ambassador
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
